repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
    -   id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.287'
    hooks:
    -   id: ruff
        args: ["--ignore", "E501"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ["-ll"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
    -   id: python-safety-dependencies-check
        files: requirements\/[a-z]+\.txt
