repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-case-conflict
        fail_fast: true
    -   id: check-merge-conflict
        fail_fast: true
    -   id: debug-statements
        fail_fast: true
    -   id: detect-aws-credentials
        fail_fast: true
        args: ["--allow-missing-credentials"]
    -   id: detect-private-key
        fail_fast: true

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        fail_fast: true

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        fail_fast: true
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.254'
    hooks:
    -   id: ruff
        fail_fast: true
        args: ["--ignore", "E501"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
    -   id: bandit
        fail_fast: true
        args: ["-ll"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
    -   id: python-safety-dependencies-check
        fail_fast: true
        files: requirements\/[a-z]+\.txt
