version: "3"
services:
  api:
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - PGRST_DB_URI=${DATABASE_URL}
    image: postgrest/postgrest
    ports:
      - 3000:3000

  postgres:
    env_file:
      - .env
    image: postgres:10-alpine
    ports:
      - 5432:5432

  processing:
    build: processing
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./data:/mnt/data
      - ./processing:/mnt/code

  web:
    build: web
    command: ["npm", "run", "dev"]
    depends_on:
      - api
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=diario.serenata.ai
    ports:
      - 8080:8080
    volumes:
      - ./web:/mnt/code
      - /mnt/code/node_modules
