version: "3"
services:
  api:
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - PGRST_DB_URI=${DATABASE_URL}
    image: postgrest/postgrest:v0.4.4.0
    ports:
      - 3000:3000

  postgres:
    env_file:
      - .env
    image: postgres:11.3-alpine

  processing:
    build: processing
    depends_on:
      - postgres
      - rabbitmq
      - redis
    env_file:
      - .env
    volumes:
      - ${DATA_FOLDER}:/mnt/data
      - ${PROCESSING_FOLDER}:/mnt/code

  rabbitmq:
    image: rabbitmq:3.7.15-alpine

  redis:
    image: redis:5.0.5-alpine

  web:
    build: web
    command: ["npm", "run", "dev"]
    depends_on:
      - api
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=diario.serenata.ai
    ports:
      - 8080:8080
    volumes:
      - ./web:/mnt/code
      - /mnt/code/node_modules
