version: "3"
services:
  api:
    image: postgrest/postgrest
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - PGRST_DB_URI=${DATABASE_URL}
    ports:
      - 3000:3000

  data_collection:
    build: data_collection
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./data:/mnt/data
      - ./data_collection:/mnt/code
      - ./database:/mnt/lib/database

  postgres:
    env_file:
      - .env
    image: postgres:alpine
    ports:
      - 5432:5432

  processing:
    build: processing
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./database:/mnt/lib/database
      - ./processing:/mnt/code

  web:
    build: web
    depends_on:
      - api
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./web:/mnt/code
      - /mnt/code/node_modules
